name: Build and release kernel packages
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "!.github"
      - ".github/workflows/build.yml"
      - "!README*"
      - "!.gitignore"
      - "!synobuild"
defaults:
  run:
    # required to get `-eo pipefail`
    shell: bash

jobs:
  fix-srcinfo-and-sums:
    name: Push fixed .SRCINFO and update pkgbuild checksums
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      # makepkg fails even for printsrcinfo if uid==0 or if the src dir isn't writable.
      - name: Initialize pacman & get git
        run: |
          pacman-key --init
          pacman -Sy git --noconfirm
        # WARN: not doing -Syu, so technically installing anything is UB, but what is being installed seems harmless
        # and -Syu MULTIPLE TIMES per run is wasteful.
      - name: Create build user
        run: |
          useradd -m user
          echo 'user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: unavoidable git dubious ownership workaround
        run: git config --global --add safe.directory "$(realpath .)"
      - name: Regenerate .SRCINFO
        run: |
          chmod o+w .  # or makepkg dies right away
          sudo -u user makepkg --printsrcinfo > .SRCINFO
          git add .SRCINFO
      - name: Fix pkgbuild checksums
        run: |
          pacman -S pacman-contrib --noconfirm
          # updpkgsums is impl'd in terms of makepkg so it can't run as root.
          # also means user needs write perms to pkgbuild.
          chmod o+w PKGBUILD
          sudo -u user updpkgsums
      - name: Commit and push
        run: |
          if [ -z "$(git ls-files -m)" ]; then exit 0; fi
          git config --global user.name "GitHub Actions"
          git config --global user.email "null@bot"
          git commit -a -m "bot chore: update .SRCINFO and pkgbuild sums"
          git push

  makepkg:
    name: Build Arch packages
    needs: fix-srcinfo-and-sums
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v4
        with:
          # TODO bad weird hack: srcinfo job might push, moving the branch that triggered this from aaa to bbb.
          # but actions/checkout will still read aaa here from the workflow info. we want bbb though.
          # this workd forcing ref to main because this workflow is only triggered on main. it's a stupid bug if any other
          # branches are ever enabled though.
          ref: main

      # makepkg fails even for printsrcinfo if uid==0 or if the src dir isn't writable.
      - name: Create build user
        run: |
          useradd -m user
          echo 'user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
      - name: Chown repo to build user
        run: chown --recursive user .

      - name: Ensure .SRCINFO is up to date
        run: |
          sudo -u user makepkg --printsrcinfo > /tmp/.SRCINFO
          diff .SRCINFO /tmp/.SRCINFO

      - name: Get upstream PGP keys
        # this is very sensitive to choice of keyserver per key.
        # keyserver.ubuntu.com should be the gpg default now.
        # linus' key isn't found with either server lol.
        # TODO why is there the keys/ dir in here? what is the threat model?
        run: |
          sudo -u user gpg --keyserver hkps://keys.openpgp.org --recv-keys A2FF3A36AAA56654109064AB19802F8B0D70FC30
          sudo -u user gpg --recv-keys ABAF11C65A2970B130ABE3C479BE3E4300411886 647F28654894E3BD457199BE38DBBDC86092693E B8AC08600F108CDF
      - name: Bootstrap pacman
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
      - name: Install github-cli
        # github-cli does not depend on git; lolsob
        run: pacman -S git github-cli --noconfirm
      - name: Run makepkg
        run: sudo -u user MAKEFLAGS="$MAKEFLAGS -j$(nproc)" makepkg -s --noconfirm
      # somehow gh can't see the git repo after makepkg.
      - name: Create release
        # TODO propagate package version to tag name
        run: |
          tar cvf /tmp/packages.tar linux-syno*.pkg.*
          # TODO same fragile hack as earlier: workflow trigger SHA isn't post srcinfo-fix SHA, so use rev-parse HEAD to see the local SHA
          gh release create --repo ${{ github.repository }} "$(git rev-parse HEAD)" /tmp/packages.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
