name: makepkg
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: create build user
        run: useradd user
      - name: git checkout
        uses: actions/checkout@v4
      - name: chown repo to user
        run: chown --recursive user "${{ github.workspace }}"
      - name: makepkg
        working-directory: ${{ github.workspace }}
        run: su -c 'makepkg -s' user
