name: makepkg
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Bootstrap pacman
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
      - name: Create build user
        run: |
          useradd user
          echo 'user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
      - name: Clone repo
        uses: actions/checkout@v4
      # based on dumb experiments, cwd here is /__w/blabla/... the full checkout dir,
      # and github.workspace is completely wrong and doesn't exist.
      - name: Chown repo to build user
        run: chown --recursive user .
      - name: Run makepkg
        run: sudo -u user makepkg -s --noconfirm --skippgpcheck
