name: makepkg
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: create build user
        run: useradd user
      - name: git checkout
        uses: actions/checkout@v4
      - name: debug ls'ing
        run: |
          echo github.workspace: `${{ github.workspace }}`
          echo work:
          ls -la ~/work
          echo __w:
          ls -la /__w
      - name: wtf is at github.workspace a.k.a. `${{ github.workspace }}` ?
        run: ls -la "${{ github.workspace }}"
      - name: chown repo to user
        run: chown --recursive user "${{ github.workspace }}"
      - name: makepkg
        working-directory: ${{ github.workspace }}
        run: su -c 'makepkg -s' user
