name: Create an upstream merge PR every so often
on:
  schedule:
  - cron: "17 17 * * *"
  workflow_dispatch:
  push:
    paths: ".github/workflows/upstream-pr-bot.yml"

env:
  UPSTREAM_REMOTE: "https://gitlab.archlinux.org/archlinux/packaging/packages/linux.git"
  UPSTREAM_REF: main
  BRANCH_NAME: "actions-merge-upstream-${{ github.run_id }}"
permissions:
  # writing the pr topic branch is writing to the real repo...
  contents: write
  # pull-requests: write is gated behind a repo settings UI-only checkbox for "allow PR creation and approval by Actions"!
  pull-requests: write
jobs:
  job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      # a necessary component of `gh pr new` is having a unique branch already created with the commits on it.
      # how to clean these branches up?
      - run: | 
          git config user.name upstream-pr-bot
          git config user.email upstream-pr@bot
      - run: git checkout -b "$BRANCH_NAME"
      # don't know if it's guaranteed that main always points to latest tagged release,
      # but if it isn't I don't know what else to do.
      # allow-unrelated-histories isn't needed at a local cli so not sure what's different here.
      - run: git pull --no-commit --no-rebase -s ort -X ours "$UPSTREAM_REMOTE" "$UPSTREAM_REF"
        # no-rebase is REQUIRED (or rebase or ff-only), just one of them is usually already set locally in user's global cfg.
        # no-commit supports removing .SRCINFO; alternative would be commit --amend later.
        # ort ours vs theirs I'm not sure what's best, but just choose something so that we have a commit no matter what.
      # this automerge commit will 100% have wrong content in the pkgbuild, e.g. ignoring anything related to the new version number!
      # user just has to know that a commit (maybe amend) is needed. how can this be automated?
      # the wrongness of pkgbuild also means there is no point regenerating .SRCINFO or checksums right now.
      # in fact let's just delete .SRCINFO to avoid diff noise. another bot run can just generate it.
      - run: |
          if [ -s "$(git status --short)" ]; then
            git rm -f .SRCINFO
            git commit  # assuming the pull --no-commit left a commit message
            git push -u origin "$BRANCH_NAME"  # gh is supposed to auto-push, but it doesn't work non-interactively
            gh pr create --draft --body "Please fix this bad automerge and then bring it into main\!"
          fi
