name: Create an upstream merge PR every so often
on:
  schedule:
  - cron: "17 */6 * * *"
  workflow_dispatch:
  push:
    paths: ".github/workflows/upstream-pr-bot.yml"

env:
  UPSTREAM_REMOTE: "https://gitlab.archlinux.org/archlinux/packaging/packages/linux.git"
  UPSTREAM_REF: main
  BRANCH_NAME: "actions-merge-upstream-${{ github.run_id }}"
permissions:
  # writing the pr topic branch is writing to the real repo...
  contents: write
  # pull-requests: write is gated behind a repo settings UI-only checkbox for "allow PR creation and approval by Actions"!
  pull-requests: write
jobs:
  job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # crucial for git to perform merges, otherwise it sees zero history of this project and considers everything unrelated
      - name: Read upstream repo
        run: |
          git fetch "$UPSTREAM_REMOTE" "$UPSTREAM_REF"
          echo "Local rev:    $(git rev-parse HEAD)"
          echo "Upstream rev: $(git rev-parse FETCH_HEAD)"
      - name: Attempt automerge
        # this automerge commit will 100% have wrong content in the pkgbuild, e.g. ignoring anything related to the new version number!
        # user just has to know that a commit (maybe amend) is needed. how can this be automated?
        # TODO learn gh actions job state and outputs and stuff...
        run: |
          if [ -n "$(git branch --list "$(git branch --show-current)" --no-contains FETCH_HEAD)" ]; then
            # ^ docs are confusing, but via experimentation --contains works, --merged doesn't.
            git checkout -b "$BRANCH_NAME"  # --track is insane; will assoc to origin/main, not origin/BRANCH_NAME
            # even with --no-commit, git merge will unalive itself without user name set.
            git config user.name upstream-pr-bot
            git config user.email upstream-pr@bot
            git merge --no-commit -s ort -X ours FETCH_HEAD
            ./automerge-steps.sh
            #git merge --continue
            # ^ dies due to "dumb terminal, please use -m", but with --continue it straight up refuses to parse any other cli args and dies.
            # --no-edit on the merge does not help. so, back to plain commit with a -m message.
            git commit -m "merge $(git rev-parse FETCH_HEAD) from $UPSTREAM_REMOTE"
            git push -u origin "$BRANCH_NAME"
            gh pr create --draft --fill --body "Please fix this bad automerge and then bring it into main\!"
          fi
